DEFAULT_SETTINGS_LOCATION = "settings/defaults"
DEFAULT_DQN_SETTINGS_FILE = DEFAULT_SETTINGS_LOCATION + "/" + "dqn_defaults.yml"
DEFAULT_A3C_SETTINGS_FILE = DEFAULT_SETTINGS_LOCATION + "/" + "a3c_defaults.yml"
DEFAULT_ADQN_SETTINGS_FILE = DEFAULT_SETTINGS_LOCATION + "/" + "adqn_defaults.yml"
